{{ if or (.is_x11) (.is_wayland) -}}
[".local/share/fonts/Symbols-1000-em Nerd Font Complete.ttf"]
  type = "file"
  url  = "https://github.com/ryanoasis/nerd-fonts/raw/master/src/glyphs/Symbols-1000-em Nerd Font Complete.ttf"
[".local/share/fonts/codicon.ttf"]
  type = "file"
  url  = "https://github.com/microsoft/vscode-codicons/raw/main/dist/codicon.ttf"
[".local/share/backgrounds/dotachina.png"]
  type = "file"
  url = "https://github.com/ram02z/backgrounds/raw/master/dotachina.png"
{{- end}}
