{{ if or (.is_x11) (.is_wayland) -}}
[".local/share/fonts/SymbolsNerdFont-Regular.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/v2.3.3/patched-fonts/NerdFontsSymbolsOnly/complete/Symbols-1000-em Nerd Font Complete.ttf"
[".local/share/fonts/codicon.ttf"]
  type = "file"
  url = "https://github.com/microsoft/vscode-codicons/raw/main/dist/codicon.ttf"
[".local/share/backgrounds/dotachina.png"]
  type = "file"
  url = "https://github.com/ram02z/backgrounds/raw/master/dotachina.png"
[".icons/Simp1e-dark"]
  type = "archive"
  url = "https://github.com/ram02z/Simp1e-dark/archive/master.tar.gz"
  exact = true
  stripComponents = 1
{{-   if and (.is_wayland) (not (lookPath "grimshot")) -}}
[".local/bin/grimshot"]
  type = "file"
  url  = "https://github.com/swaywm/sway/raw/master/contrib/grimshot"
  executable = true
{{-   end }}
{{- else if (eq .os_id "darwin") -}}
["Library/Fonts/Symbols-1000-em Nerd Font Complete.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/821ac68173a9651cb5ca788996c18273de994f95/src/glyphs/Symbols-1000-em Nerd Font Complete.ttf"
["Library/Fonts/codicon.ttf"]
  type = "file"
  url = "https://github.com/microsoft/vscode-codicons/releases/latest/download/codicon.ttf"
{{- end }}
