# TODO: icons?
[menu]
executable = 'rofi'
args = [
    '-dmenu',
    '-markup-rows',
    '-format p',
    '-p {prompt}',
]

[format]
window_format = '{urgency_start}<b>“{title}”</b>{urgency_end} — <i>{app_name}</i> <span alpha="20000">({id})</span>'
workspace_format = '<b>Workspace {name}</b>   <span alpha="20000">({id})</span>'
html_escape = true
urgency_start = '<span background="darkred" foreground="yellow">'
urgency_end = '</span>'
# icon_dirs = [
#     '/usr/share/icons/hicolor/48x48/apps',
#     '/usr/share/pixmaps',
# ]
