[icons]
"firefox-default" = ""
foot = ""
copyq = ""
iwgtk = ""
"com.github.quaternion" = ""
libreoffice-writer = ""


[general]
default_icon = ""
separator = " "

[options]
no_names = true
remove_duplicates = true
