idle_bg = "#282a36"
idle_fg = "#f8f8f8"
info_bg = "#282a36"
info_fg = "#bd93f9"
good_bg = "#282a36"
good_fg = "#50fa7b"
warning_bg = "#282a36"
warning_fg = "#f1fa8c"
critical_bg = "#282a36"
critical_fg = "#ff5555"
separator = "|"
separator_bg = "auto"
separator_fg = "#44475A"
# alternating_tint_bg = "#111111"
# alternating_tint_fg = "#000000"
