name: Formating

on:
  push:
    branches:
      - master
    paths:
      - 'dot_config/nvim/**.lua'

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --glob **/*.lua -- dot_config/nvim/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: format with stylua"
          branch: ${{ github.head_ref }}
