[theme]
name = "dracula"

[icons]
name = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "apt"
interval = 1800
format_singular="{count:1}"
format = "{count:1}"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
on_click = "i3-quickterm upgrades" 

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
marquee_interval = 0
marquee_speed = 0.25
dynamic_width = true
separator = " "
on_click = "i3-quickterm mpsyt"
on_collapsed_click = "i3-quickterm mpsyt" 
interface_name_exclude = ["firefox"]

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"
on_click = "gnome-system-monitor"

[[block]]
block = "memory"
format_mem = "{mem_used_percents:2}"
format_swap = "{mem_used;M}"
clickable = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "sound"
max_vol = 100
show_volume_when_muted = false

[[block]]
block = "weather"
format = "{temp}"
autolocate = true
service = { name = "openweathermap", api_key = "8865f0dc0c6c3b4f0fc601fd063f5be1", place = "Harrow", units = "metric" }
on_click = "gnome-weather"

# Airpods
[[block]]
block = "bluetooth"
label = " Pods"
mac = "14:60:CB:C7:B4:2A"
format_unavailable = ""
hide_disconnected = true

# Bose QC35s
[[block]]
block = "bluetooth"
label = " QC35"
mac = "60:AB:D2:42:04:74"
format_unavailable = ""
hide_disconnected = true
# on_click = "i3-nagbar -m $(based-connect -b 60:AB:D2:42:04:74) -type warning"

# [[block]]
# block = "net"
# format = "{signal_strength}"
# on_click = "gnome-control-center network"

[[block]]
block = "networkmanager"
on_click = "i3-quickterm nmtui"
primary_only = true
device_format = "{icon}{ap}"
ap_format = "{strength}"

[[block]]
block = "custom"
command = ''' rofication-json '''
interval = 5
on_click = "rofication-gui"
hide_when_empty = true
json = true

[[block]]
block = "battery"
format = "{percentage}"
on_click = "gnome-power-statistics"

[[block]]
block = "time"
interval = 1 
format = "%R"
on_click = "gnome-calendar"
icons_format = " "
